### ISSUE TITLE
~remindme module?

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#31]
Copy from QQQ likely.
https://github.com/kevslinger/ravenclaw-discord-bot

Integrate with countdown feature too probably

**Comment by kevslinger** [comment]
Reminder module in QQQ [here](https://github.com/kevslinger/ravenclaw-discord-bot/tree/main/modules/reminder). Needs some tuning, and for BBN we would push a reminder table to the database instead of using a google sheet, but definitely doable. Would want to involve the time parser from [time_utils](https://github.com/kevslinger/bot-be-named/blob/e89bdf506d9e817ecbc24a236825606f33e88a75/modules/time/time_utils.py#L18)

**Comment by TheOriginalSoni** [comment]
Done in f91a4a4

**Comment by TheOriginalSoni** [comment]
> Reminder module in QQQ [here](https://github.com/kevslinger/ravenclaw-discord-bot/tree/main/modules/reminder). Needs some tuning, and for BBN we would push a reminder table to the database instead of using a google sheet, but definitely doable. Would want to involve the time parser from [time_utils](https://github.com/kevslinger/bot-be-named/blob/e89bdf506d9e817ecbc24a236825606f33e88a75/modules/time/time_utils.py#L18)

Splitting this to #83
